background_opacity 0.65
shell /usr/bin/fish

# Fonts

## main font
font_family JetBrainsMono Nerd Font Mono
## Japanese fallback
symbol_map U+3000-U+30FF Noto Sans Mono CJK JP
symbol_map U+4E00-U+9FFF Noto Sans Mono CJK JP
symbol_map U+FF00-U+FFEF Noto Sans Mono CJK JP

# Emoji fallback
symbol_map U+1F300-U+1FAFF Noto Color Emoji

disable_ligatures always

# New tab in current directory
map ctrl+shift+enter launch --type=tab --cwd=current

# <C-space> = ESC
map ctrl+space send_text all \x1b

# fixing fullscreening on startup
remember_window_size no
