wallpaper {
    monitor =  DP-2
    path = /home/martin/Pictures/Wallpapers/QHD
    timeout = 120
}
wallpaper {
    monitor =  HDMI-A-1
    path = /home/martin/Pictures/Wallpapers/QHD
    timeout = 120
}
wallpaper {
    monitor =  HDMI-A-2
    path = /home/martin/Pictures/Wallpapers/QHD
    timeout = 120
}
splash = false
